title: Product Name
description: McNeel theme for GitHub Pages.
show_downloads: true
google_analytics:
# theme: jekyll-theme-minimal

# email: alain@mcneel.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "/eto-layouts/" # the subpath of your site, e.g. /blog/
url: "https://scotttd.github.io/eto-layouts/" # the base hostname & protocol for your site
nwo: "scotttd/eto-layouts" # github repository (name with owner)

# If we decide that we want to use kramdown over redcarpet, syntax
# highlighting is performed by turning on the following options and
# including/running highlight.js (https://highlightjs.org/) at the
# top of pages that need it (probably just add to head.html)
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
      disable: true
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo

#port: 4444

safe: true

collections:
  - guide_topics
  - api
  - samples
  - videos

collections:
  guide_topics:
    output: true
    permalink: /guides/:path/
  api:
    output: true
    permalink: /api/:path/
  samples:
    output: true
    permalink: /samples/:path/
  videos:
    output: true
    permalink: /videos/

exclude: [/script, /test, README.md, CONTRIBUTING.md, Gemfile]